### ISSUE TITLE
Unexpected behavior when adding/removing first character

### ISSUE THREAD

**Issue by srijken** [guilhermegeek/angular-bootstrap-validation#1]
For a testcase demonstrating the problem see: http://plnkr.co/edit/PCNfs8HHBnqa9MgQ6ifx

**Comment by gui-com-pt** [comment]
Sorry for the delay to respond. I haven't touched this library for a while, i'll check this issue and also refactor the code to improve it adding unit tests. I'll push it to branch 2.0-dev

**Comment by gui-com-pt** [comment]
Too long ago. Will check again if anyone asks.
